services:
  - type: web
    name: menacesearch-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        value: 8712904392:AAGMl7OBly82D2zD7Wt2vyfjqSg4B4nfio8